:PROPERTIES:
:ID:       74939DD6-1FE3-44CF-8172-C191F9077EB4
:END:
#+title: 20241216-20241222
#+filetags: :info:weekly:


* 1、 优等生的局限性

第一个局限，是任何人都具有的局限，是身份、层次、位置带来的局限性。伟大的事业离不开人群基础，但优等生不仅不了解自身之外的人们，还认为自己就是成功者而不愿与他人共事。

第二个局限，来自于排名思维下不成熟的优越感。真正可怕的是长期形成的“人可以排序”的思维方式。

第三个局限，是经历的多样性不够。

第四个局限，是缺少血性，只敢在框架内行事。

[[https://mp.weixin.qq.com/s/K-0i4on3MqeaZSAz-J73HA][优等生的局限性]]


* 2、一个人行动力不足的原因是选择模糊

焦虑的反义词是具体。当你把一天要做的任务拆解成一个一个非常具体可执行的小目标时，你就对自己具备了掌控感，自然也就行动力拉满了。

[[https://m.okjike.com/originalPosts/674f21a78d6dd8c09cc93f6e][一个人行动力不足的原因是选择模糊。 大多数人觉得自己行动力 - 即刻App]]


* 3、生活支点越多，内核越稳

所谓的「支点」，就是那些让你在失败和不如意的时候，仍然能托住你的东西。
支撑你的事物真的有很多，它们一直都在，只是你需要花些时间想起它们。

[[https://m.okjike.com/originalPosts/67568df9e35d19168cad8b3d][特别赞同「生活支点越多，内核越稳」这句话。 是从周轶君老师 - 即刻App]]


* 4、用微积分的思维过生活， 不用太精确，接受生活、事业的模糊性

微分思维：一点一点地活，不求完美。用微分思维去生活，就是把生活拆解成一个个小的瞬间、一个个具体的行动，而不被遥远的目标或终极意义压垮。小步快跑，积少成多：生活中的每一个小行动都是一个微分，每一点点努力都会让你向目标靠近。允许不精确：微分本身是局部的、近似的，生活也是如此。我们不需要每一步都完美，只需要“差不多”地前进，慢慢调整。

积分思维：累积的力量，回头看一切都有意义。不要急于看到结果，而是相信那些琐碎的、日常的努力，最终会产生质变。积分可以容许误差，生活也一样。即使某些地方没做好，也不会影响最终的整体方向。

不用太精确：接受生活的模糊性。生活不需要“精确解”：我们无法预测未来，也无法完全掌控生活的每一个细节。只要方向大致正确，模糊的努力也能带来好的结果。允许调整和修正：微积分的计算中，经常需要调整参数、改变方法。生活中，我们也可以随时修正自己的目标和做法，不必执着于某一个固定的计划。

[[https://m.okjike.com/originalPosts/6757989c8d6dd8c09c5dc668][用微积分的思维过生活， 不用太精确，接受生活、事业的模糊性。 - 即刻App]]


* 5、四大知识管理系统

Zettelkasten 系统：源自德国社会学家卢曼的这套方法，也被称为「卡片盒笔记法」。

Linking Your Thinking (LYT) 代表了知识管理的现代演进。Nick Milo 提出的这个系统特别强调通过建立思想间的联系来创建知识网络，并创新性地引入了内容地图（MOCs）概念来组织笔记。

PARA 系统是由知识管理专家 Tiago Forte 提出的一个极具实用性的框架。它通过将信息分为项目（Projects）、领域（Areas）、资源（Resources）和存档（Archives）四个维度，创建了一个清晰而实用的信息组织结构。

Johnny Decimal 系统提供了一个独特的数字化文件组织方案，更适合将其运用到文件系统和知识库的整体架构设计中。通过限制每个层级最多包含 10 个类别的严格结构，它为个人知识管理提供了一个清晰的框架。这个系统很像是图书馆的杜威十进制分类法，都采用了数字编码来组织信息。

[[https://letter.justgoidea.com/p/weekly-spark-no-7][Weekly Spark No.7 | 壹苇可航]]


* 6、不要看与自己无关的信息，去爱自己，关注自己，把时间和精力都专注在自己身上

在这个网络爆炸的时代，你一天的信息量相当于古人一年的，但事实上90%的信息都与你自己无关。

要知道过多关注别人，不会让你变得更好，只会消耗自己的能量，让自己变得疲倦。

[[https://x.com/jiamimaodashu/status/1867554710406017262][@jiamimao 猫叔 on X: "真心建议所有人，不要看与自己无关的信息，去爱自己，关注自己，把时间和精力都专注在自己身上。 在这个网络爆炸的时代，你一天的信息量相当于古人一年的，但事实上90%的信息都与你自己无关。" / X]]


* 7、擦边主播聊一聊吴柳芳事件背后的擦边经济学

[[https://www.bilibili.com/video/BV1fSiDYMETH/][擦边主播聊一聊吴柳芳事件背后的擦边经济学_哔哩哔哩_bilibili]]

[[https://www.youtube.com/watch?v=GX9lKEzm3MY][擦边女主播聊吴柳芳事件背后的擦边经济学 - YouTube]]


* 8、人生最大的经验

一切都是命，当你面对一件事情时，按照你过往的性格和逻辑，会做出的行为，这个就是命。 如果事情发生的时候，你做出的行力，不符合自己过往的性格习惯，有了很大的偏差这个就叫运。所以，运是改变，命是定数。

不要总遗憾过去，按当时的心智，只要不是带着记忆重生，回到过去的节点，大概率还是会走当年的老路。

世界就是一个草台班子，不要这不敢那不敢的，干就完事，凡事你能接触到的人，再牛也牛不到哪儿去。

人生的容错度非常高，很多你以为“完蛋了”的事情其实也就那样；年轻时不要等待，要去争。

永远不要揣摩别人的想法，觉得不舒服的关系就走 别回头。

[[https://m.okjike.com/originalPosts/675d97b8f0513f13169b383b][小红书上有一个近100w人浏览过的帖子，标题叫“目前为止你总 - 即刻App]]


* 9、用随机梯度下降来优化人生

要有目标；目标要大；坚持走，不管你的目标多复杂，随机梯度下降都是最简单的；痛苦的卷，每一步里你都在试图改变你自己或者你的模型参数，改变带来痛苦，但没有改变就没有进步；可以躺平；四处看看，每一步走的方向是你对世界的认识；快也是慢，你没有必要特意去追求找到最好的方向和最合适的步子；赢在起点，如果你在终点附近起步，可以少走很多路，而且终点附近的路都比较平，走着舒服；很远也能到达，如果你是在随机起点，那么做好准备前面的路会非常不平坦，越远离终点，越人迹罕见，四处都是悬崖；独一无二；简单最好。

[[https://zh.wikipedia.org/zh-cn/%E6%A2%AF%E5%BA%A6%E4%B8%8B%E9%99%8D%E6%B3%95][梯度下降法 - 维基百科，自由的百科全书]]

[[https://zhuanlan.fxzhihu.com/p/414009313][用随机梯度下降来优化人生 | FxZhihu]]


* 10、第一性原理

1）、家庭的第一性原理，是经济，而不是感情。
2）、职场的第一性原理，是价值，而不是努力。
3）、教育的第一性原理，是培养能力，而不是追求分数。
4）、健康的第一性原理是自律，而不是医疗。
5）、创业的第一性原理，是市场需求，而不是个人喜好。
6）、投资的第一性原理，是风险控制，而不是高回报。
7）、养老的第一性原理，是提前规划，而不是依赖子女。
8）、成长的第一性原理，是反思，而不是经历。

[[https://m.okjike.com/originalPosts/67627d21cc17b0c5d36d8780][1、家庭的第一性原理，是经济，而不是感情。 2、职场的第一性 - 即刻App]]


* 11、梁宁老师《真需求》

价值源自需求，因为被需求，所以有价值。
在商业世界里生存的方法：创造价值，取得共识，获得资源，强化竞争力，构建生存的优势。
你能连接的人，不是你的人脉；你能帮到的人，才是你的人脉。
交易是单次的共识，关系是多次长久的共识。
“买单”是检验需求的唯一标准。
产品价值=功能价值 + 情绪价值 + 资产价值
情绪价值=生理唤起 + 认知标记 + 心理账户
资产价值=专门交易市场(及服务)x对手共识(价值与价格依赖)
情绪价值的三个付费要素：保障感、愉悦感、彰显性
撬动改变的公式：不满情绪 × 愿景 × 第一步 > 改变的阻力

[[https://m.okjike.com/originalPosts/674a039bf0513f13164780d1][梁宁老师《真需求》 ，推荐！ ⭐️ 人们放弃一件事，原因往 - 即刻App]]


* 12、E165 对话半佛仙人：目标、成本、收益、风险

人生是一条单行道。既然人生的起点和人生的终点都是一样的，那中间的过程，理论上只要你喜欢，越花里胡哨越好。  
人生是旷野，旷野代表没有目的性，你要找到属于你的目的。想清楚你的目的，和你的努力统一，并能承担选择的代价。
没有想清楚、没有意义的事情就不做。
别把自己太当回事，这个世界不是所有人都按照你的想法来生活。
不是只有把事做好才算天赋，你能坚持不懈的做一件事情并且不痛苦，这就是一种天赋。喜欢是一种天赋，能把它玩好是另一种天赋。找到你喜欢且能坚持的东西。
任何策划，第一个想到的是天才，第二个想到的是大笨蛋。但如果你是一个新人，还没有做过内容，先从模仿开始。
商业内容账号接不到广告，说明你做的都是垃圾，因为市场不承认。
作为专业的创作者，要走出流量幻觉。流量不值钱，值钱的是带属性（有场景、足够垂直）、与商业贴近的流量。
做一切东西都需要让更多的人看到。每个人都应该想办法把自己自媒体化，因为这是普通人唯一的机会（现在还有）。
我们活在物质世界里，没有执行，观念世界产生不了实际的钱。

[[https://www.xiaoyuzhoufm.com/episode/6735a29af373fe5d4d3a2627][E165 对话半佛仙人：搞懂这八个字，人生，易如反掌🤚🏻 - 知行小酒馆 | 小宇宙 - 听播客，上小宇宙]] 
