:PROPERTIES:
:ID:       BA42BF56-8E02-4D44-B0BE-60F7F4CB279A
:END:
#+title: 20241125-20241201
#+filetags: :weekly:info:


* 1、 打工的唯一目的就是偷师！！

[[https://m.okjike.com/originalPosts/673d21a58f1c3c9ff51f2c21][打工的唯一目的就是偷师！！ 近期的一个新洞察，公司会设置各 - 即刻App]]


* 2、 建议不要沉湎在向内探索的无底洞里。

瑞士著名的心理学家卡尔·荣格曾经说过，人生分为上半场和下半场，每个人都会经历一场从自我（ego）到本我（self）的转变。

上半场的时候，是由自我（ego）主导的向外生长，其目的是为了形成一个健康的自我。

人生的下半场，你需要完成与潜意识同行的向内探索，并学会放下。

对于大部分人而言，上半场要做的只有一件事，和世界周旋。

因为自我的形状是在和世界的碰撞中形成的。

[[https://m.okjike.com/originalPosts/6737401bf0513f1316050c49][建议不要沉湎在向内探索的无底洞里。 很多人容易过早迷恋向内 - 即刻App]]


* 3、付出就想马上有回报，适合做钟点工。

期望能按月得到报酬，适合做打工族。

耐心按年度领取年收入，是职业经理人。

能耐心等待三到五年，适合做投资家。

用一生的眼光去权衡，你就是企业家。

[[https://m.okjike.com/originalPosts/674431dbcc17b0c5d360657f][付出就想马上有回报，适合做钟点工。 期望能按月得到报酬，适 - 即刻App]]


* 4、进步最快的几种方式

找榜样，一帧一帧对比你和他的不同。所谓的精通，基本都来自于大量的重复。要让足够好的东西，在你的眼睛里停留足够长的时间。

如果精力有限，先在一件小事情上找到正反馈。

把体力和精力，看成和工作事业一样重要的一环，认真对待。

[[https://hwv430.blogspot.com/2024/11/blog-post_20.html][核电站: 进步最快的几种方式]]


* 5、拖延的一部分原因是，自己预判到成功率比较低，就老是去想怎么成功的问题，想不明白就一直拖着，直到不了了之。

做事的人，上来就干，失败了就解决问题，解决问题了又有下一个问题，没时间精力内耗。

[[https://x.com/dontbesilent12/status/1857825315202187648][dontbesilent on X: "我现在觉得做事拖延，和失败观有很大关系 失败越快，成功越快，做事应该尽可能快速地拿到负反馈 拖延的一部分原因是，自己预判到成功率比较低，就老是去想怎么成功的问题，想不明白就一直拖着，直到不了了之" / X]]


* 6、Career Advice

If you want something extraordinary, you have two paths:
1）. Become the best at one specific thing. 
2）. Become very good (top 25%) at two or more things.

The first strategy is difficult to the point of near impossibility. Few people will ever play in the NBA or make a platinum album. I don’t recommend anyone even try.

The second strategy is fairly easy. Everyone has at least a few areas in which they could be in the top 25% with some effort.

[[https://dilbertblog.typepad.com/the_dilbert_blog/2007/07/career-advice.html][The Dilbert Blog: Career Advice]]


* 7、做选择的黄金法则: 做时间的朋友。

时间是最强大的价值乘数。与时间为友,本质上是选择那些能够随着时间推移而持续产生、甚至加速产生价值的路径。

做选择时,不应只问"现在能得到什么",还要问"这个选择会让时间站在我这边吗"。

[[https://m.okjike.com/originalPosts/674967c3f0513f13163cccd5][做选择的黄金法则: 做时间的朋友。 时间是最强大的价值乘数 - 即刻App]]
