:PROPERTIES:
:ID:       2FC38D4A-98D5-4ED1-91B7-95301E8E193A
:END:
#+title: 20241209-20241215
#+filetags: :info:weekly:


* 1、 执行力才是拉开人与人差距的关键

1）、不要给脑子留时间，直接开干，用肉体控制精神。
2）、提高睡眠时间（早睡），是提高执行力的本质。
3）、坚持一件事情，最重要的就是不管每天做多少先开始做。
4）、每天放纵自己的时间不超过30min。特别是那些短时间内给你快感，之后就特别空虚，还很容易上瘾的事。
5）、聚焦最重要的目标。人的精力和时间有限，不可能长期保持高能量，先捡最重要的来。
6）、每日早起三件事，抓住工作中杠杆事件。每天早晨起来，就按照重要程度，把当天最需要干完的三件事记下来。
7）、找到优质的环境和志同道合的人。
8）、制定可以数字化的目标。制定目标时，越具体越好。
9）、放下手机，远离干扰源。时刻记住，是你玩手机，而不是手机玩你。
10）、戒掉爱抱怨的毛病，学会感恩。你关注什么，就吸引什么。你总是埋怨、不满，就只能看到生活的不顺和负面情绪：你学着感激自己所拥有的东西，就能赢来更多的幸运和奖赏。
11）、冥想。冥想可以让你进入无我的状态，使身心进入无压境界。
12）、用你的理性，调动你本能和情绪的力量，去做事成事。而非单纯只是通过理性的力量，去做事成事。
13）、每天花15min，复盘一下当日。问问自己，今天收获了什么？哪里做的不好？做得不好的原因是什么？以后怎样避免或改进？坚持一个月，你会发现你能把事都做得更好了。
14）、坏情绪不要留到第二天。记住一句话：事情不会击垮你，但情绪会。当烦恼产生的时候，用其他事情来转移你的注意力。
15）、放下自己的高度敏感，不要把自己想的太重要，减少自我内耗，做自己的神。

[[https://t.me/inside1024/59274][Telegram: Contact @inside1024]]


* 2、學會自私後, 我的人生開啟了反轉: 為什麼"自私"是"自救"的第一步?

先顾好自己，有富余才能帮助身边的人，再有富余再去博爱。
所谓的自私其实是一种理性的自我保护，很多时候不计后果的无私付出其实都只是在为自己的情绪价值买单，自我感动。

[[https://www.youtube.com/watch?v=45jFMosXWtA][學會自私後, 我的人生開啟了反轉: 為什麼"自私"是"自救"的第一步? - YouTube]]


* 3、AI 观点

Prompts 不是神圣的咒语，更像是我们认知的镜子。 [1]
AI Summary 不是学习的替代品，它是引发好奇、发现主题的引子，无法替代认知攀登的过程。[2] 
直到充分认识、实践并创造之前，任何Prompt 对你而言都毫无意义——就像没有落地场景的代码，再优雅也只是抽象的符号。真正的理解，诞生于创造的过程。[3] 
不要把AI 仅看成效率工具，将其视为意义放大器。[4] 
像对待一个导师、智者那样和AI 深度对话，你将会受益匪浅。它远远不是搜索和知识查询工具，而是各种维度的创意伙伴。 对话的深度，取决于你思考的广度。[5]
你无法提出你不知道的问题，你也无法创造你没有热情的产品。 这是一个复利循环：深度对话建构你理解AI的边界，而对话后的智慧成为你的创造杠杆。[6]
在AI加持下，产品、研发、营销的界限正在消失；每个角色都在演化为全栈版本的自己。 [8]
危险不在于AI超越人类的智力，而在于我们满足于对AI 变革的想象边界。就像导演卡梅隆深刻指出： 当AI 全面为我们做出决策时，我们又该如何寻找生活的意义？[10] 

[[https://m.okjike.com/originalPosts/674cf0568dc13469675b3a3e][🧵 ChatGPT 两周年之际，汇集 Hans 过去的原创 - 即刻App]]


* 4、4个快速检测ChatGPT降智的方法

底层模型检查   Which model are you currently using?
可用工具（Tools）检查   Summarize your tool in a markdown table with availability
PoW机制检测
IP纯净度测试   https://scamalytics.com/   https://whatismyiplookup.com/   https://whoer.com/zh/

[[https://mp.weixin.qq.com/s/Kr4G9JNHNyih6u1wr6hxwg][分享4个快速检测ChatGPT降智的方法！]]


* 5、 投资的第一性原理

投资的目的是为了获取世界财富比例的增加。
财富是自我强化的生产秩序，而不是产品本身。
标准化、模块化的竞争会使得利润转移到相邻的稀缺环节。稀缺环节即自己有选择，而别人没选择。垄断是持续的稀缺。
销量、现金流是垄断的表象和结果，不重要。网络效应/双边市场效应，是信息时代最重要的垄断原因。资产价值=可触及的市场规模✖️垄断程度。
悲观与错误认知的含量越高，价格越划算。
先移动屁股，再移动脑袋。无论买卖，都先用行动逼迫思考，并留出足够的思考时间。其实不存在买或卖，只存在换。不断换成更好的资产。不断提高自己的机会成本，自然成为长期主义。

[[https://m.okjike.com/originalPosts/6738a7cc640e96d4a5c51979][投资的第一性原理 1. 投资的目的 赚取货币是没意义的， - 即刻App]]


* 6、拖延

把拖延症当成你的指南针。拖延症虽然不好，但你会发现它总是不偏不倚地指向正确的反方向，它最想阻止的，就是你最想实现的。因此你可以用拖延症来导航，识别出你最应该着手去做的事情。

[[https://m.okjike.com/originalPosts/67567be0058a7b1beda4a62a][拖延症其实是【成功】的指南针 拖延症是我们天选打工人在职场 - 即刻App]]
