:PROPERTIES:
:ID:       BDB7BD23-7C12-4A8D-9549-6C504A8A6FEB
:END:
#+title: 202501
#+filetags: :monthly:info:


* 1、 2024

[[https://en.wikipedia.org/wiki/2024][2024 - Wikipedia]]

[[https://zh.wikipedia.org/wiki/2024%E5%B9%B4][2024年 - 维基百科，自由的百科全书]]


* 2、 大大方方地去做任何事

作为自己人生的主角，就应该大大方方做任何事。

克服对矛盾冲突的逃避胆怯；克服对自我的虚假道德约束

[[https://m.okjike.com/originalPosts/6770ae76d102f773a449f238][强烈建议大家大大方方地去做任何事 定期给自己列缺点清单，发 - 即刻App]]


* 3、 穷真的是因为懒吗？

“我完全没有任何精力去思考脱困的方法，每天工作17个小时，我脑子里想着的只有吃饭”。

精力管理比时间更重要

穷和富是一个人的环境，想法，教育，机遇等综合结果

[[https://m.okjike.com/originalPosts/67709a56887087ba0463ff2f]["穷真的是因为懒吗？" 香港以前有个节目叫《穷富豪大作战》 - 即刻App]]


* 4、 用这个列表去回归复盘一年生活

Part 1: 生活事件与目标反思
Part 2: 情感与人际关系
Part 3: 兴趣与创造力
Part 4: 提升自我意识与影响力
Part 5: 总结与展望

[[https://m.okjike.com/originalPosts/677352b048988025c530aa3d][2024年快结束了，可以试着用这个列表去回归复盘一年生活： - 即刻App]]


* 5、 庆山 《一切境》

如果人不阅读，只是偶尔从网络、电视或其他载体形式获取新闻、信息、资讯，不会带来提升思辨能力的途径。相反形成头脑中更多引发焦虑与分辨的自我抗争。只有保持长期的、有主题性的、系统而深度的阅读，进行有序的整理与思考，才有可能形成某种思维突破。思维突破之后，才会带来身语意整体层面的提升。

[[https://m.okjike.com/originalPosts/677223b4ff53ca73dee85f65][「如果人不阅读，只是偶尔从网络、电视或其他载体形式获取新闻、 - 即刻App]]


* 6、《把日子过好》 龙飞律师

永远不要为了谁放弃自己的成长，你必须要有能力，要有钱，要有能挣钱的才华，你才可能拥有真正的幸福和自由。

[[https://weibo.com/6421571119/P7YxBt9hR][#果麦日签# 永远不... - @知书少年果麦麦的微博 - 微博]]


* 7、 拥有比金钱珍贵百倍的【筹码】

即便被生活逼到了墙角，你也永远拥有不止一个选择。
如果生活里有太多烦恼，这些烦恼占据了有限的精力，就没有足够的精力“带宽”来做出明智的决策了。

[[https://m.okjike.com/originalPosts/6773698fb8e0dfdbabe02e73][你其实早就拥有比金钱珍贵百倍的【筹码】 最近看了一篇202 - 即刻App]]


* 8、 2025年，我的一点小建议

保持有营养的信息摄入：把更多的时间分配给主动阅读。
练习放松的身体状态
试着允许自己慢下来：多听少说，少评判、少反驳、少输出。
 养成随时锻炼的习惯：锻炼身体，是目前已知唯一能够提升我们精力上限的方式。
尝试使用不同的思维方式
建立一个每天长期耕耘的时间

不断去优化和调整我们的「生活系统」的做法。系统不是设计出来的，而是调校出来的。

[[https://mp.weixin.qq.com/s/UYphA64B0KoPai0uGwLnWA][2025年，我的一点小建议]]


* 9、 使用 ChatGPT 原理学会一切知识

首先要有目标：目标函数，也叫成本函数，损失函数。模型训练的目标就是让损失函数最小化。
学习目标要大：个人学习的目标，是缩小bok2和bok1之间的差距，形成你自己的更全面更扎实更强大的bok2。
从实例中学习
用高质量信息作为学习数据：Garbage in，garbage out。这是机器学习的第一性原理。
从错误中学习：预测下一个 token => 得出error => 反向传播 => 梯度下降 => 调整参数 => 预测下一个 token
唯有学习才能改变自己：短时记忆就是大脑突触之间神经递质增加释放，长时记忆就是基因表达蛋白质合成折叠，形成新的突触连接。
把阅读作为学习方法：人类学习者，需要首先成为一个贪婪的阅读者：一年五十本书。每天至少阅读一小时。
把费曼作为理解方法：首先费曼知识砖块，然后不断费曼知识砖块之间的关联。通过清晰的概念以及概念之间的关联，人类形成自己的理解。
把迭代作为进步方法：闭环，迭代，这是学习之要义。
规模法则，大力出奇迹
身为父母，减少人为干预
注意力是最贵的：机器通过注意力机制实现了更强大的认知能力。而人类的注意力却愈发稀缺和脆弱。短视频是免费的，但是，注意力却是最贵的。
预训练之外的后训练：后训练：微调（finetuning），奖励建模（reward modeling）和RLHF(基于人类反馈的强化学习)。预训练占比95%，是绝对大头；后训练强调少而精，事半功倍。
言行就是思维本身
学习，快与慢的艺术：以知识树为目标的学习，在快与慢之间最容易取得平衡：前期快速搭建框架，快速建立大局观，获得正反馈；然后慢慢微调，一个概念接着一个概念，看起来慢，但实现了更好的快。
学习，没有人出生在罗马
学习，每个人有自己的时区
学习，简洁是更高级的复杂

[[https://mp.weixin.qq.com/s/2iFD6wy3E_C28kGA2XKRgQ][使用 ChatGPT 原理学会一切知识]]


* 10、 段永平浙大分享

坚持做对的事情，不被短期诱惑。短期诱惑是错事的核心诱因，发现错了就该立刻停。
回归本质和目的，学会筛选信息。不要让知识量压垮你，真正有用的，是学会筛选和理解。
不追求角色定义，为用户需求负责。时代一直在变，但做对的事不会变。

[[https://m.okjike.com/originalPosts/677a9bdbb8e0dfdbab5fd4f6][听完段永平浙大分享，我收获了3个思维方式 1 坚持做对的事 - 即刻App]]


* 11、 永远保持可以离开的能力

[[https://m.okjike.com/originalPosts/67776c10887087ba04e13a21][永远保持可以离开的能力 进入老板圈子之后，才深刻理解作为员 - 即刻App]]


* 12、 2024年的10个思考

做事情一定要有主线
身体是长期主义的起点
少生气，多复盘
主动选择圈子，主动拥抱变化
为价值而不是性价比花钱
与原生家庭的边界感，是成年人必须的修行
时刻觉察是否进入碎片化的时间黑洞
长期主义最重要的底层逻辑是行动

[[https://m.okjike.com/originalPosts/6775340d34e603afef48e4e8][2024年的10个思考 1 做事情一定要有主线 上半年摆 - 即刻App]]


* 13、 自学的误解

误解：自学不需要计划
误解：可以完全靠自己解决问题
误解：免费资源就足够了
误解：进步一定是线性的
误解：只靠记忆就能掌握知识
误解：只需靠动力就能坚持
误解：自学适合所有人
误解：学习速度越快越好
误解：失败就是浪费时间
误解：只要足够努力就一定成功

[[https://x.com/actualize2100/status/1874489033428275267][actualize2100🌍 on X: "自学是一种强大的学习方式，但人们对它往往存在一些常见的误解，这些误解可能导致期望不当或效果不佳： 1. 误解：自学不需要计划 •误区：认为自学只要有兴趣就可以随时开始，无需明确目标或学习计划。 •实际情况： •没有计划的学习往往杂乱无章，容易半途而废。" / X]]


* 14、 Measuring personal growth

Try to become a new person every 3-6 years.
Try to solve big problems as fast as possible. I think of this as creating safety nets that allow me to take bigger risks and explore more things in the future.

[[https://huyenchip.com//2024/04/17/personal-growth.html][Measuring personal growth]]


* 15、Less is more

[[https://yinji.org/5366.html][Less is more - 印记]]


* 16、抖音大脑，与劣质多巴胺的狂飙时代

自律的本质，是优质多巴胺。

[[https://mp.weixin.qq.com/s/7K3Y4eVlY3rBlb5WQoKQ-A][抖音大脑，与劣质多巴胺的狂飙时代]]


* 17、 7个习惯帮你掌控人生节奏——从内耗到高效的思维训练

习惯1：积极主动——情绪稳定，是最高级的自律
        刺激与回应之间存在一段距离，成长和幸福的关键就在这里。
习惯2：以终为始——目标清晰，才能高效规划
习惯3：要事第一——摆脱瞎忙，抓住关键任务
        分不清轻重缓急的人，注定活在混乱中。
习惯4：双赢思维——共赢才是最长久的胜利
习惯5：知己知彼——首先理解他人，然后再寻求被理解
        倾听不是在等待说话的机会，而是为了理解对方的世界。
习惯6：综合统效——协作共创，让1+1>2
习惯7：不断更新——持续成长，拒绝停滞

[[https://m.okjike.com/originalPosts/677a55697b0ec1ac86032709][《7个习惯帮你掌控人生节奏——从内耗到高效的思维训练》 今 - 即刻App]]


* 18、 每个人每天都只有24小时，希望我的选择真的是我的选择

“社会规范”的更新是滞后的，而社会变革是超前的。这就解释了为什么我们学校教育的“家国理想”，市场需要的“商业技能”，和家庭提倡的“传统责任”，会有相当程度的不同，以及它们之间产生的张力对学生时代的我们造成的不同方向上的拉扯。

接受多巴胺的驱动，很舒服。随大流，很舒服。而向内探索，拨开层层保护，找到真正想要的东西，很痛苦。但无论是随大流的痛苦还是向内探索的痛苦，都是值得庆幸的。因为如果不了解这个世界“存在另一种可能”的话，就不会产生痛苦。

人生是自己的。每个人每天都只有24小时。选择做什么是我的选择，但我希望确保真的是我的选择。

My goal for the future isn’t to avoid mistakes, it’s for the mistakes I do make to be my own.

[[https://justinyan.me/post/5790][每个人每天都只有24小时，希望我的选择真的是我的选择 | 枫言枫语]]


* 19、 Cursor 使用思路

[[https://x.com/s1ntone/status/1880052416374304785][sintone on X: "很多人吐槽 Cursor 只能用来做小玩具，做大项目没法用。也有很多人认为它非常高效，做大项目没问题。 🪄我有一个魔法 PROMPT，能帮助你瞬间改变 Cursor 使用思路，从小白变成高工。 ⏰我从去年 Cursor https://t.co/ULJMsFcklZ" / X]]


* 20、 公式

生命 = 当下 x (觉知 + 行动) ^ 超越
死亡 = (灵魂: 自由) AND (肉体: 消亡)
健康 = (运动 AND 睡眠 AND 饮食 AND 情绪 AND 用药) x 平衡度
睡眠质量 = (动力 x 能力 x 环境) - 干扰因素
幸福 = MIN(意义, 健康, 关系) x 当下
意义 = (使命 → 专注 → 成就) x 持续性
关系 = (信任 AND 边界 AND 合作) x 维护
心态 = 觉察 → 接纳 → 调节
人际 = (本分 + 利他) x 边界
家庭 = (包容 AND 责任 AND 陪伴) x 持续投入
亲密关系 = (无条件的爱 AND 非暴力沟通 AND 肢体性亲密) x 维系度
孩子成长 = (无条件的爱 AND 环境 AND 榜样) x 时间
决策 = (信息 + 分析 + 直觉) x 担当
情绪稳定性 = 格局 / 触发源
学习效果 = 理解深度 x 实践次数


* 21、 为什么我们常常理性上非常认同某个道理，行动上却很难知行合一？

解决方案就是放弃对无痛的幻想，直接接纳沮丧。

不要对抗，不要拖延，直接就接纳沮丧，沮丧就会消失得很快，身体能量就会被释放出来，你就会觉得自己更有力量去接受新的现状，去知行合一。

[[https://m.okjike.com/originalPosts/67a6a67317d46f6fd6da2d3d][为什么我们常常理性上非常认同某个道理，行动上却很难知行合一？ - 即刻App]]


* 22、 毁掉我们的不是我们所憎恨的，恰恰是我们所热爱的。

臃肿的身体，退化的思维，涣散的注意力……都是在透支你的人生。

每次为了低级的快感而放纵，都意味着你选择了堕落和妥协；每次为了高级的快乐而克制，都意味着你变得更理智、更强大。

每个人的命运，本质上都是自己下意识行为的总和。

[[https://x.com/HotmailfromSH/status/1889837773642932282][Dr.Wang on X: "“毁掉我们的不是我们所憎恨的，恰恰是我们所热爱的。” 臃肿的身体，退化的思维，涣散的注意力……都是在透支你的人生。 每次为了低级的快感而放纵，都意味着你选择了堕落和妥协； 每次为了高级的快乐而克制，都意味着你变得更理智、更强大。 每个人的命运，本质上都是自己下意识行为的总和… https://t.co/K06N9NjtAY" / X]]
