:PROPERTIES:
:ID:       BDB7BD23-7C12-4A8D-9549-6C504A8A6FEB
:END:
#+title: 20241230-20250105
#+filetags: :info:weekly:


* 1、 2024

[[https://en.wikipedia.org/wiki/2024][2024 - Wikipedia]]

[[https://zh.wikipedia.org/wiki/2024%E5%B9%B4][2024年 - 维基百科，自由的百科全书]]


* 2、 大大方方地去做任何事

作为自己人生的主角，就应该大大方方做任何事。

克服对矛盾冲突的逃避胆怯；克服对自我的虚假道德约束

[[https://m.okjike.com/originalPosts/6770ae76d102f773a449f238][强烈建议大家大大方方地去做任何事 定期给自己列缺点清单，发 - 即刻App]]


* 3、 穷真的是因为懒吗？

“我完全没有任何精力去思考脱困的方法，每天工作17个小时，我脑子里想着的只有吃饭”。

精力管理比时间更重要

穷和富是一个人的环境，想法，教育，机遇等综合结果

[[https://m.okjike.com/originalPosts/67709a56887087ba0463ff2f]["穷真的是因为懒吗？" 香港以前有个节目叫《穷富豪大作战》 - 即刻App]]


* 4、 用这个列表去回归复盘一年生活

Part 1: 生活事件与目标反思
Part 2: 情感与人际关系
Part 3: 兴趣与创造力
Part 4: 提升自我意识与影响力
Part 5: 总结与展望

[[https://m.okjike.com/originalPosts/677352b048988025c530aa3d][2024年快结束了，可以试着用这个列表去回归复盘一年生活： - 即刻App]]


* 5、 庆山 《一切境》

如果人不阅读，只是偶尔从网络、电视或其他载体形式获取新闻、信息、资讯，不会带来提升思辨能力的途径。相反形成头脑中更多引发焦虑与分辨的自我抗争。只有保持长期的、有主题性的、系统而深度的阅读，进行有序的整理与思考，才有可能形成某种思维突破。思维突破之后，才会带来身语意整体层面的提升。

[[https://m.okjike.com/originalPosts/677223b4ff53ca73dee85f65][「如果人不阅读，只是偶尔从网络、电视或其他载体形式获取新闻、 - 即刻App]]


* 6、《把日子过好》 龙飞律师

永远不要为了谁放弃自己的成长，你必须要有能力，要有钱，要有能挣钱的才华，你才可能拥有真正的幸福和自由。 ​​​ 

[[https://weibo.com/6421571119/P7YxBt9hR][#果麦日签# 永远不... - @知书少年果麦麦的微博 - 微博]]


* 7、 拥有比金钱珍贵百倍的【筹码】

即便被生活逼到了墙角，你也永远拥有不止一个选择。
如果生活里有太多烦恼，这些烦恼占据了有限的精力，就没有足够的精力“带宽”来做出明智的决策了。

[[https://m.okjike.com/originalPosts/6773698fb8e0dfdbabe02e73][你其实早就拥有比金钱珍贵百倍的【筹码】 最近看了一篇202 - 即刻App]]


* 8、 2025年，我的一点小建议

保持有营养的信息摄入：把更多的时间分配给主动阅读。
练习放松的身体状态
试着允许自己慢下来：多听少说，少评判、少反驳、少输出。
 养成随时锻炼的习惯：锻炼身体，是目前已知唯一能够提升我们精力上限的方式。
尝试使用不同的思维方式
建立一个每天长期耕耘的时间

不断去优化和调整我们的「生活系统」的做法。系统不是设计出来的，而是调校出来的。

[[https://mp.weixin.qq.com/s/UYphA64B0KoPai0uGwLnWA][2025年，我的一点小建议]]


* 9、 使用 ChatGPT 原理学会一切知识

首先要有目标：目标函数，也叫成本函数，损失函数。模型训练的目标就是让损失函数最小化。
学习目标要大：个人学习的目标，是缩小bok2和bok1之间的差距，形成你自己的更全面更扎实更强大的bok2。
从实例中学习
用高质量信息作为学习数据：Garbage in，garbage out。这是机器学习的第一性原理。
从错误中学习：预测下一个 token => 得出error => 反向传播 => 梯度下降 => 调整参数 => 预测下一个 token
唯有学习才能改变自己：短时记忆就是大脑突触之间神经递质增加释放，长时记忆就是基因表达蛋白质合成折叠，形成新的突触连接。
把阅读作为学习方法：人类学习者，需要首先成为一个贪婪的阅读者：一年五十本书。每天至少阅读一小时。
把费曼作为理解方法：首先费曼知识砖块，然后不断费曼知识砖块之间的关联。通过清晰的概念以及概念之间的关联，人类形成自己的理解。
把迭代作为进步方法：闭环，迭代，这是学习之要义。
规模法则，大力出奇迹
身为父母，减少人为干预
注意力是最贵的：机器通过注意力机制实现了更强大的认知能力。而人类的注意力却愈发稀缺和脆弱。短视频是免费的，但是，注意力却是最贵的。
预训练之外的后训练：后训练：微调（finetuning），奖励建模（reward modeling）和RLHF(基于人类反馈的强化学习)。预训练占比95%，是绝对大头；后训练强调少而精，事半功倍。
言行就是思维本身
学习，快与慢的艺术：以知识树为目标的学习，在快与慢之间最容易取得平衡：前期快速搭建框架，快速建立大局观，获得正反馈；然后慢慢微调，一个概念接着一个概念，看起来慢，但实现了更好的快。
学习，没有人出生在罗马
学习，每个人有自己的时区
学习，简洁是更高级的复杂

[[https://mp.weixin.qq.com/s/2iFD6wy3E_C28kGA2XKRgQ][使用 ChatGPT 原理学会一切知识]]
