:PROPERTIES:
:ID:       7313fb5f-0994-4f95-a4d3-5fd4fed3c95f
:END:
#+title: 202504
#+filetags: :info:monthly:


* 1、 Ali Abdaal - 值得长期坚持的8个健康小习惯

1）321睡眠法🛏️
睡前3小时不进食物
睡前2小时不喝水、饮料
睡前1小时不看电子产品

2）日行万里步👣
不要久坐，最好保持每日10000+的步数
在时间紧迫、工作繁忙的情况下，也要尽可能多走走

3） Meditation冥想🧘‍♀️
有时间的时候，做5-10分钟的冥想

4）半年记一次健康数据
DEXA身体数据 记录专业的数据（比如肌肉量、脂肪量，还可以知道自己是哪个身体部位出现了问题，控制营养、健康数据等）

5）Protein蛋白质
摄入一定的蛋白质，才可以gain muscles＆lose fats

6）Stretching拉伸运动
做一个20min左右的拉伸运动，找到不错的拉伸运动跟练视频，下午来一个精神放松和身体拉伸，超棒！

7）便携药盒
如果你有特定需要吃的药物，可以买一个有周周日期标注的便携药盒，上面还有不同的颜色标注，就不容易忘啦~

8）护肤相关

[[https://www.bilibili.com/video/BV1Hx4y1f71v/][Ali Abdaal - 值得长期坚持的8个健康小习惯｜冥想 睡眠 拉伸 营养 护肤 体检_哔哩哔哩_bilibili]]


* 2、 每个人本质上只关注一个东西：自己

我们无法真正"成为"他人，无法直接体验他人的内在世界。所有的体验、所有的认知，必然是"我的"体验，"我的"认知。即使当我们试图理解他人时，我们实际上是在自己的意识剧场中上演一出关于他人的戏剧。

那「利他」行为呢？我们做「好事」是因为这符合我们对自我的理解，满足我们的价值需求，甚至仅仅是为了避免愧疚感——这些都是自我系统的内部运作。

我们永远无法逃离自我的引力场，但可以不断扩大这个引力场的半径。不是消灭自我，而是扩展自我，直到"他"与"我"的界限变得模糊。

[[https://m.okjike.com/originalPosts/67cc76f8dc6b6d4853fee174][每个人本质上只关注一个东西：自己。 我们无法真正"成为"他 - 即刻App]]


* 3、 穷人为什么难翻身

1）成熟晚
2）没有建设性的指导
3）没有试错资本

[[https://m.okjike.com/originalPosts/67fa29217cb8c547e2956b11][穷人为什么难翻身？ 1、成熟晚 他们中大多要到30多岁， - 即刻App]]


* 4、 人到中年怎么进步

减少不必要的社交，很多社交都是无意义的社交，社交本质是利益交换，自己的实力如果不够强，认识再多的人都没用，因为自己对别人没什么价值，别人也不会和你交换什么。

不要忌妒，不要比较，不会悔恨。为什么？一切的内耗都源于最开始的起心动念，当年起心动念去揣测别人的时候，别人并不会为你改变，但是你却花了很多自己宝贵的时间在内心中内耗，时间是这个世界上最公平也是最宝贵的东西。而人性，只有你非常强大的时候，他们才会尊重你。

不要迷恋奉承和成就，人性是，喜欢造神，也更喜欢亲自推倒神，看神倒塌。中年以后，认真搞钱，踏踏实实做事情，保持低调，只和最重要的几个人沟通。这就是余生的福报。

[[https://manateelazycat.github.io/2025/04/24/focus-self/][人到中年怎么进步？]]
